name: main
on:
  pull_request:
    branches:
      - master
    types: [closed]
  push:
    branches:
      - master

jobs:
  build_and_push:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            CONFIG_FILE=${{ github.ref == 'refs/heads/dev' && 'config.dev.yml' || 'config.prod.yml' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
